src/Entity/Entreprise.php
<?php

namespace App\Entity;

use App\Repository\EntrepriseRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: EntrepriseRepository::class)]
class Entreprise
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 50)]
    private ?string $nom_entreprise = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $adresse = null;

    #[ORM\Column(length: 20)]
    private ?string $telephone = null;

    #[ORM\ManyToMany(targetEntity: Client::class, inversedBy: 'entreprises')]
    private Collection $clients;

    public function __construct()
    {
        $this->clients = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNomEntreprise(): ?string
    {
        return $this->nom_entreprise;
    }

    public function setNomEntreprise(string $nom_entreprise): static
    {
        $this->nom_entreprise = $nom_entreprise;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    public function setAdresse(string $adresse): static
    {
        $this->adresse = $adresse;

        return $this;
    }

    public function getTelephone(): ?string
    {
        return $this->telephone;
    }

    public function setTelephone(string $telephone): static
    {
        $this->telephone = $telephone;

        return $this;
    }

    /**
     * @return Collection<int, Client>
     */
    public function getClients(): Collection
    {
        return $this->clients;
    }

    public function addClient(Client $client): static
    {
        if (!$this->clients->contains($client)) {
            $this->clients->add($client);
        }

        return $this;
    }

    public function removeClient(Client $client): static
    {
        $this->clients->removeElement($client);

        return $this;
    }
}

src/Form/EntrepriseType.php
<?php

namespace App\Form;

use App\Entity\Client;
use App\Entity\Entreprise;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class EntrepriseType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nom_entreprise')
            ->add('adresse')
            ->add('telephone')
           
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Entreprise::class,
        ]);
    }
}

src/Controller/EntrepriseController.php
<?php

namespace App\Controller;

use App\Entity\Entreprise;
use App\Form\EntrepriseType;
use App\Repository\EntrepriseRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Http\Attribute\IsGranted;

#[Route('/entreprise')]
#[IsGranted('ROLE_ADMIN')]
class EntrepriseController extends AbstractController
{
    #[Route('/', name: 'app_entreprise_index', methods: ['GET'])]
    public function index(EntrepriseRepository $entrepriseRepository): Response
    {
        return $this->render('entreprise/index.html.twig', [
            'entreprises' => $entrepriseRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_entreprise_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $entreprise = new Entreprise();
        $form = $this->createForm(EntrepriseType::class, $entreprise);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($entreprise);
            $entityManager->flush();

            return $this->redirectToRoute('app_entreprise_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('entreprise/new.html.twig', [
            'entreprise' => $entreprise,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_entreprise_show', methods: ['GET'])]
    public function show(Entreprise $entreprise): Response
    {
        return $this->render('entreprise/show.html.twig', [
            'entreprise' => $entreprise,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_entreprise_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Entreprise $entreprise, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(EntrepriseType::class, $entreprise);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_entreprise_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('entreprise/edit.html.twig', [
            'entreprise' => $entreprise,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_entreprise_delete', methods: ['POST'])]
    public function delete(Request $request, Entreprise $entreprise, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$entreprise->getId(), $request->request->get('_token'))) {
            $entityManager->remove($entreprise);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_entreprise_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/entreprise/_delete_form.html.twig
<form method="post" action="{{ path('app_entreprise_delete', {'id': entreprise.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ entreprise.id) }}">
    <button class="btn btn-outline-danger">Supprimer</button>
</form>

templates/entreprise/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-primary">{{ button_label|default('Enregistrer') }}</button>
{{ form_end(form) }}

templates/entreprise/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Entreprise{% endblock %}

{% block body %}
    <h1>Modifier les informations Entreprise</h1>

    {{ include('entreprise/_form.html.twig', {'button_label': 'Enregistrer'}) }}

    <a href="{{ path('app_entreprise_index') }}">revenir à la liste</a>

    {{ include('entreprise/_delete_form.html.twig') }}
{% endblock %}

templates/entreprise/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Entreprise {% endblock %}

{% block body %}
    <h1>Liste des Entreprises </h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Nom</th>
                <th>Adresse</th>
                <th>Téléphone</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
        {% for entreprise in entreprises %}
            <tr>
                <td>{{ entreprise.id }}</td>
                <td>{{ entreprise.nomEntreprise }}</td>
                <td>{{ entreprise.adresse }}</td>
                <td>{{ entreprise.telephone }}</td>
                <td>
                    <a href="{{ path('app_entreprise_show', {'id': entreprise.id}) }}">voir</a>
                    <a href="{{ path('app_entreprise_edit', {'id': entreprise.id}) }}">modifier</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_entreprise_new') }}">Ajouter une entreprise</a>
{% endblock %}

templates/entreprise/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Entreprise{% endblock %}

{% block body %}
    <h1>Ajouer une Entreprise</h1>

    {{ include('entreprise/_form.html.twig') }}

    <a href="{{ path('app_entreprise_index') }}">revenir à la liste</a>
{% endblock %}

templates/entreprise/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Entreprise{% endblock %}

{% block body %}
    <h1>Entreprise</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ entreprise.id }}</td>
            </tr>
            <tr>
                <th>Nom_entreprise</th>
                <td>{{ entreprise.nomEntreprise }}</td>
            </tr>
            <tr>
                <th>Adresse</th>
                <td>{{ entreprise.adresse }}</td>
            </tr>
            <tr>
                <th>Telephone</th>
                <td>{{ entreprise.telephone }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_entreprise_index') }}">revenir à la liste</a>

    <a href="{{ path('app_entreprise_edit', {'id': entreprise.id}) }}">modifier</a>

    {{ include('entreprise/_delete_form.html.twig') }}
{% endblock %}